<?php
/**
 * Document download.
 *
 * Files live outside the web root, so this script is the only way to
 * reach one. That is deliberate: if uploads were served straight from a
 * public folder, knowing (or guessing) a filename would be enough, and
 * the permission check below would never run.
 *
 * The order matters — authenticate, authorise, resolve the path, then
 * stream. Nothing is echoed before all three have passed.
 */

declare(strict_types=1);

require_once __DIR__ . '/includes/includes.inc.php';

$user      = require_login();
$controler = new Controler();

$document = $controler->document(get_int('id'));

if ($document === null) {
    http_response_code(404);
    exit('File not found.');
}

// A client may only read their own record. Staff may read anything —
// that is the job. Note this compares against the session, never
// against anything the request supplied.
$isOwner = (int) $document['owner_id'] === (int) $user['id'];

if ($user['role'] !== 'admin' && !$isOwner) {
    http_response_code(403);
    exit('You do not have access to that file.');
}

// basename() on the stored name is belt and braces: stored names are
// generated by us and contain no separators, but a path built from a
// database value should still never be able to walk out of its folder.
$path = DOCUMENTS_PATH . '/' . basename((string) $document['stored_name']);

if (!is_file($path) || !is_readable($path)) {
    error_log('[download] missing file on disk for document #' . $document['id']);
    http_response_code(404);
    exit('That file is no longer on the server.');
}

$controler->audit(
    $user,
    'document.download',
    'document',
    (string) $document['id'],
    'Downloaded ' . $document['original_name']
);

// Clear any buffered output so nothing prepends itself to the bytes.
while (ob_get_level() > 0) {
    ob_end_clean();
}

// Sent as an attachment with a fixed content type. Serving a user
// upload inline lets an .html or .svg file run script in the context of
// this site, which is a stored XSS by another name.
header('Content-Type: application/octet-stream');
header('Content-Disposition: attachment; filename="' . str_replace('"', '', (string) $document['original_name']) . '"');
header('Content-Length: ' . (string) filesize($path));
header('X-Content-Type-Options: nosniff');
header('Cache-Control: private, no-store');

readfile($path);
exit;
